In [1]:
import pandas as pd
import re
import numpy as np
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MultiLabelBinarizer
from sentence_transformers import SentenceTransformer
import ast
import json

In [ ]:
nltk.download('punkt_tab')
nltk.download('stopwords')
pip install sentence-transformers

# Load to Memory & Merge Features and Desc.

In [2]:
games_df = pd.read_csv('games.csv')

In [3]:
with open("games.json", "r", encoding="utf-8") as f:
    data = json.load(f)

In [4]:
metadata_df = pd.DataFrame.from_dict(data, orient="index").reset_index().rename(columns={"index": "app_id"})

In [5]:
games_df['appid'] = games_df['app_id'].astype(int)
metadata_df['app_id'] = metadata_df['app_id'].astype(int)

In [6]:
df = pd.merge(games_df, metadata_df, on='app_id', how='inner')

del games_df, metadata_df, data, f

In [7]:
df.drop(columns=['header_image', 'website', 'support_url', 'support_email', ], inplace=True)

In [8]:
# Show the Blank 'about_the_game' entries
df_check = df[['title','name','about_the_game']]
rows = df_check['about_the_game'].str.strip() == ''
df_check.loc[rows, 'about_the_game']

1656
1683
1944
2123
2250
2645
6454
7007
7271
7694
8401
8780
9452
9869
10630
11075
11502
12018
13178
14105
14171
14327
14505
15466
15847
16010
16447
16529
16868
16972
17151
17167
17341
19666
20651
21039
21110
21665
22386
22603
23092
23208
23813
24417
26366
28463
29005
31413
31557
32302
32533
33180
33881
34919
38346
39320
41037
Name: about_the_game, dtype: object

In [9]:
df_check['about_the_game'].isnull().sum()

0

# MultiLabelBinarizer

In [10]:
mlb = MultiLabelBinarizer()

# Convert the 'genres' column from a string representation of a list to an actual list
df['genres'] = df['genres'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

genres_matrix = mlb.fit_transform(df['genres'])

genres_df = pd.DataFrame(genres_matrix, columns=mlb.classes_)

df = pd.concat([df, genres_df], axis=1)

In [11]:
genres_df.head(5)

,Accounting,Action,Adventure,Animation & Modeling,Audio Production,Casual,Design & Illustration,Early Access,Education,Free to Play,...,Racing,Sexual Content,Simulation,Software Training,Sports,Strategy,Utilities,Video Production,Violent,Web Publishing
0,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,1,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Preprocessing

## Cleaning

In [12]:
def clean_text(text):
    # Remove Special Characters
    text = re.sub(r'[^\w\s]', '', text)

    # Sets all characters to lowercase
    text = text.lower()

    # Removes URLs beginning with https, http, or www
    text = re.sub(r'https\S+|http\S+|www\S+', '', text, flags=re.MULTILINE)
    
    return text

In [13]:
df['description_filled'] = df['about_the_game']

In [14]:
df['description_filled'] = df['description_filled'].apply(clean_text)

In [15]:
rows = df['description_filled'].str.strip() == ''

df.loc[rows, 'description_filled'] = (
    df.loc[rows, 'title'] + ' ' +
    df.loc[rows, 'genres'].apply(' '.join)
)

df.loc[rows, 'description_filled'] = df['description_filled'].apply(clean_text)

In [16]:
# Print any rows with descriptions with only whitespace characters
empty_descriptions = df[df['description_filled'].str.strip() == '']
empty_descriptions

Empty DataFrame
Columns: [app_id, title, date_release, win, mac_x, linux_x, rating, positive_ratio, user_reviews, price_final, price_original, discount_x, steam_deck, appid, name, release_date, required_age, price, dlc_count, detailed_description, about_the_game, short_description, reviews, windows, mac_y, linux_y, metacritic_score, metacritic_url, achievements, recommendations, notes, supported_languages, full_audio_languages, packages, developers, publishers, categories, genres, screenshots, movies, user_score, score_rank, positive, negative, estimated_owners, average_playtime_forever, average_playtime_2weeks, median_playtime_forever, median_playtime_2weeks, peak_ccu, tags, discount_y, Accounting, Action, Adventure, Animation & Modeling, Audio Production, Casual, Design & Illustration, Early Access, Education, Free to Play, Game Development, Gore, Indie, Massively Multiplayer, Movie, Nudity, Photo Editing, RPG, Racing, Sexual Content, Simulation, Software Training, Sports, Strategy, Utilities, Video Production, Violent, Web Publishing, description_filled]
Index: []

[0 rows x 81 columns]

In [20]:
# The app Descripition is literally null
# null_literal_descriptions = df[df['description'].str.strip() == 'null']
# null_literal_descriptions

In [17]:
# Print Fixed Descriptions
df.loc[rows, 'description_filled']

1656     gamer to game developer series 3 make a game e...
1683                       hello goodbye casual simulation
1944                                      postal 2 editor
2123                       hard west 2 action rpg strategy
2250                 sanator scarlet scarf adventure indie
2645                  game of mafia action adventure indie
6454     aokana  four rhythms across the blue adventure...
7007                       livelock action adventure indie
7271     the princess the stray cat and matters of the ...
7694     sankaku renai love triangle trouble adventure ...
8401                   sonic mania action adventure casual
8780                                     abode 2 adventure
9452     naraka bladepoint action adventure massively m...
9869            the jewel of monostructure adventure indie
10630                      overwatch 2 action free to play
11075                      elechead action adventure indie
11502    the princess the stray cat and matters of the ...
12018                  immortals of aveum action adventure
13178      sabbat of the witch adventure casual simulation
14105          souls of chronos action adventure indie rpg
14171    marco  the galaxy dragon adventure casual simu...
14327    deeeer simulator your average everyday deer ga...
14505                     my fluffy life casual simulation
15466                          rabbit riot adventure indie
15847                   quarantine rpg simulation strategy
16010                                   is defense editor
16447      star pilot action free to play indie simulation
16529    the dawning clocks of time action adventure in...
16868     one thousand lies casual free to play simulation
16972                              closed action indie rpg
17151             crazy pixel streaker action indie sports
17167                               azurea juncture casual
17341                defense grid 2 a matter of endurance
19370                          his heroes in the sky indie
19666                     halo reach mod tools  mcc action
20651    no turning back the pixel art actionadventure ...
21039                    age of empires iv content editor
21110                      7 days to die dedicated server
21665    relow action indie massively multiplayer early...
22386           boom blaster action adventure casual indie
22603                              halo ce mod tools  mcc
23092                    sleep tight action indie strategy
23208                    monochroma action adventure indie
23813                          unturned  dedicated server
24417                        piracrash action casual indie
26366                 the last tree action adventure indie
28126    aircraft carrier survival tutorial action simu...
28463                      lawnarchy casual indie strategy
29005                      alien swarm reactive drop  sdk
31413             perfectly balanced casual indie strategy
31557                                           irec indie
32302    playground action casual indie sports early ac...
32533    bloody chronicles  new cycle of death visual n...
33180            two guys one cabin action adventure indie
33881                         halo 3 mod tools  mcc action
34919         alphadeck casual free to play indie strategy
38346    star trek online free to play massively multip...
38546    neverwinter action adventure free to play mass...
39320              tainted grail conquest action indie rpg
41037                               halo 2 mod tools  mcc
Name: description_filled, dtype: object

In [19]:
# Checking Random Description Columns
pd.set_option('display.max_colwidth', None)
print(df['description_filled'].sample(n=3))
pd.reset_option('display.max_colwidth')

32169    bobok is a kinetic visual novel based on fyodor dostoyevskys short story of the same name 1873 st petersburg not the most prominent literary man was dubbed in newspapers as a madman his portrait with two phenomenally symmetrical and lively warts was to blame unheard of human stupidity surrounds the writer wishing to divert himself he enters a funeral where he begins to hear the voices of undead people maybe at least they are smarter than living ones unknown dostoevsky one of the most atypical and wierdest works of the great russian writer fyodor mikhailovich dostoevsky author of crime and punishment the brothers karamazov black humor satire grotesque and a crosssection of the authors entire oeuvre fit into a short story where fantastic madness goes hand in hand with documented reality the game is great for those who want to experience the original text glossary the handy hint system prevents you from being confused by terms and easily fills in the missing knowledge it is more convenient and informative than footnotes in books localization workshop cant find your language check out our steam workshop page where awesome community help us make literature available to everyone you can already play the game in simplified chinese and even prerevolutionary imperial russian
22336                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 bitdude is the classic story of our favorite little dotchomper but from another perspective sure eating dots and fruit to get more points seemed harmless but did you ever stop to think about their lives in bitdude players play as the bit trying to survive chompmans unrelenting hunger try to obtain the best score in each level by escorting your fellow bits to safety and noming on the fruit before chompman can
1891                                                                                                                                                                                                                                                                                                                                  the town of deadwood is being terrorized by the ghost of a murderous outlaw in ghost encounters deadwood  the collectors edition check out our new game kickass commandos  also try tiki man  also try ant war  domination  a paranormal pointandclick adventure full of intrigue grave robbers have unleashed a phantom curse and condemned the entire town one by one the townsfolk are dropping dead and now its up to you to save them explore the forsaken town of deadwood after killing 21 men while he was alive blackjack is back to kill many more  youll be at the edge of your seat trying to figure out what is coming next challenging pointandclick adventure style gameplay break blackjacks evil curse and save the day while enjoying the incredible pointandclick and hidden object puzzle adventure gameplay unique puzzles and hidden object games play your way through over 35 different locations while solving 40 puzzles and minigames in search of the ghostly villain blackjack
Name: description_filled, dtype: object

## Tokenization & Lemmatization

In [18]:
# Tokenize the descriptions
df['tokens'] = df['description_filled'].apply(word_tokenize)

# Remove Stop Words from Tokens
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

# Lemmatize the Tokens
lemmatizer = WordNetLemmatizer()
df['tokens'] = df['tokens'].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

In [19]:
# Remove Stop Words from Tokens
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda tokens: [word for word in tokens if word not in stop_words]
)

In [20]:
# Lemmatize the Tokens
lemmatizer = WordNetLemmatizer()
df['tokens'] = df['tokens'].apply(
    lambda tokens: [lemmatizer.lemmatize(word) for word in tokens]
)

# Sentance Transformer / Embeddings

In [21]:
model = SentenceTransformer('all-MiniLM-L6-v2')

# df['title'] = df['title'].fillna('')
# df['description'] = df['description'].fillna('')

# Ensure genres (which are lists) are converted to a single string before concatenation
df['labels_text'] = df.apply(
    lambda row: ' '.join(
        [*row['genres'], *row['categories']] if isinstance(row['genres'], list) and isinstance(row['categories'], list) # Return both list contents if both are lists
        else str(row['genres']) + ' ' + str(row['categories']) # Otherwise, convert the strings and append together
    ),
    axis=1 # Go row by row (not column by column)
)

texts = (df['title'] + ' ' + df['description_filled'] + ' ' + df['labels_text']).tolist()

text_embeddings = model.encode(texts, show_progress_bar=True, convert_to_numpy=True)

df['embedding'] = list(text_embeddings)

Batches:   0%|          | 0/1287 [00:00<?, ?it/s]

c:\Users\vince\anaconda3\Lib\site-packages\torch\nn\modules\module.py:1762: FutureWarning: `encoder_attention_mask` is deprecated and will be removed in version 4.55.0 for `BertSdpaSelfAttention.forward`.
  return forward_call(*args, **kwargs)

# Normalization

## Min-Max

**Applied for Ratings**

In [22]:
rating_dict = {
    'Overwhelmingly Positive': 9,
    'Very Positive': 8,
    'Positive': 7,
    'Mostly Positive': 6,
    'Mixed': 5,
    'Mostly Negative': 4,
    'Negative': 3,
    'Very Negative': 2,
    'Overwhelmingly Negative': 1
}

df['rating_normalized'] = (df['rating'].map(rating_dict) - 1) / 8

## Log Normalizing

**Applied for Positive Ratio, Price, and Review Count**

In [23]:
df['positive_ratio_log'] = np.log1p(df['positive_ratio'])
df['price_log'] = np.log1p(df['price_final'])
df['user_reviews_log'] = np.log1p(df['user_reviews'])

# Concatenating Features

In [ ]:
# df = pd.read_csv('Altered CSVs/normalized.csv')

In [ ]:
embeddings = text_embeddings

tags = genres_matrix

numerics = df[['price_log', 'positive_ratio_log', 'user_reviews_log']].values

X = np.hstack([numerics*0.6, embeddings*0.3, tags*1.7])

cs_matrix = cosine_similarity(X)

# np.save('hstack_data.npy', X)

np.save('cs_matrix.npy', cs_matrix)

# Cosine Similarity

In [26]:
# cs_matrix = np.load('cs_matrix.npy')

def recommend(df, appid, cs_matrix, k=10):
    
    index = df[df['app_id'] == appid].index[0]
    pos = df.index.get_loc(index)
    
    scores = cs_matrix[pos].copy()
    scores[pos] = -np.inf

    indexes = np.argsort(scores)[-k:][::-1]
    return df.iloc[indexes]

In [32]:
# Killing Floor 2
rec = recommend(df, 232090, cs_matrix)
rec[['app_id', 'title', 'rating', 'about_the_game', 'genres', 'categories', 'user_reviews', 'positive_ratio', 'price_final']]

,app_id,title,rating,about_the_game,genres,categories,user_reviews,positive_ratio,price_final
9772,412020,Metro Exodus,Very Positive,The year is 2036. A quarter-century after nucl...,[Action],"[Single-player, Steam Achievements, Full contr...",82022,89,30.00
38936,601150,Devil May Cry 5,Overwhelmingly Positive,The Devil you know returns in this brand new e...,[Action],"[Single-player, Multi-player, Co-op, Online Co...",71034,95,30.00
39209,1057090,Ori and the Will of the Wisps,Overwhelmingly Positive,ORI AND THE WILL OF THE WISPS IS A MUST PLAY*:...,[Action],"[Single-player, Steam Achievements, Full contr...",104440,96,29.99
38470,8870,BioShock Infinite,Very Positive,"Indebted to the wrong people, with his life on...",[Action],"[Single-player, Steam Achievements, Full contr...",99379,93,30.00
39108,883710,Resident Evil 2,Overwhelmingly Positive,The genre-defining masterpiece Resident Evil 2...,[Action],"[Single-player, Steam Achievements, Full contr...",93910,97,40.00
8825,235460,METAL GEAR RISING: REVENGEANCE,Overwhelmingly Positive,Developed by Kojima Productions and PlatinumGa...,[Action],"[Single-player, Steam Achievements, Full contr...",53864,95,30.00
11257,782330,DOOM Eternal,Very Positive,Hell’s armies have invaded Earth. Become the S...,[Action],"[Single-player, Multi-player, PvP, Online PvP,...",153466,91,40.00
39324,1196590,Resident Evil Village,Overwhelmingly Positive,Experience survival horror like never before i...,[Action],"[Single-player, Steam Achievements, Full contr...",65621,95,40.00
9393,594650,Hunt: Showdown,Very Positive,"HUNT TOGETHER. DIE ALONE. The year is 1895, an...",[Action],"[Multi-player, PvP, Online PvP, Co-op, Online ...",136385,83,40.00
38659,287390,Metro: Last Light Redux,Very Positive,It is the year 2034. Beneath the ruins of post...,[Action],"[Single-player, Steam Achievements, Full contr...",49996,89,19.99

In [33]:
# ELDEN RING
rec = recommend(df, 1245620, cs_matrix)
rec[['app_id', 'title', 'rating', 'about_the_game', 'genres', 'categories', 'user_reviews', 'positive_ratio', 'price_final']]

,app_id,title,rating,about_the_game,genres,categories,user_reviews,positive_ratio,price_final
10023,239140,Dying Light,Overwhelmingly Positive,From the creators of hit titles Dead Island an...,"[Action, RPG]","[Single-player, Multi-player, PvP, Online PvP,...",283604,95,30.00
11474,524220,NieR:Automata™,Very Positive,/ NieR: Automata tells the story of androids 2...,"[Action, RPG]","[Single-player, Steam Achievements, Steam Trad...",86896,87,40.00
38784,397540,Borderlands 3,Very Positive,"The original shooter-looter returns, packing b...","[Action, RPG]","[Single-player, Multi-player, Co-op, Online Co...",95243,85,60.00
38533,49520,Borderlands 2,Overwhelmingly Positive,A new era of shoot and loot is about to begin....,"[Action, RPG]","[Single-player, Multi-player, Co-op, Steam Ach...",184041,95,20.00
38529,48700,Mount & Blade: Warband,Overwhelmingly Positive,"In a land torn asunder by incessant warfare, i...","[Action, RPG]","[Single-player, Multi-player, Steam Achievemen...",118732,97,19.99
9846,335300,DARK SOULS™ II: Scholar of the First Sin,Very Positive,We are currently in the process of restoring t...,"[Action, RPG]","[Single-player, Multi-player, Co-op, Steam Ach...",60296,85,20.00
38718,337000,Deus Ex: Mankind Divided,Mostly Positive,"The year is 2029, and mechanically augmented h...","[Action, RPG]","[Single-player, Steam Achievements, Full contr...",27356,75,29.99
9431,678960,CODE VEIN,Very Positive,RISE TOGETHER Team up with an AI partner or a ...,"[Action, RPG]","[Single-player, Multi-player, Co-op, Online Co...",37382,85,60.00
39428,1328670,Mass Effect™ Legendary Edition,Very Positive,One person is all that stands between humanity...,"[Action, RPG]","[Single-player, Steam Achievements, Full contr...",35486,91,60.00
7010,236430,DARK SOULS™ II,Very Positive,We are currently in the process of restoring t...,"[Action, RPG]","[Single-player, Multi-player, Co-op, Steam Ach...",28182,88,20.00

In [34]:
# Titanfall 2
rec = recommend(df, 1237970, cs_matrix)
rec[['app_id', 'title', 'rating', 'about_the_game', 'genres', 'categories', 'user_reviews', 'positive_ratio', 'price_final']]

,app_id,title,rating,about_the_game,genres,categories,user_reviews,positive_ratio,price_final
38820,438740,Friday the 13th: The Game,Mostly Positive,Gameplay Friday the 13th: The Game is a third-...,[Action],"[Multi-player, Steam Achievements, Full contro...",62757,79,5.00
9434,550,Left 4 Dead 2,Overwhelmingly Positive,"Set in the zombie apocalypse, Left 4 Dead 2 (L...",[Action],"[Single-player, Multi-player, PvP, Online PvP,...",574470,97,10.00
11731,381210,Dead by Daylight,Very Positive,Death Is Not an Escape. Dead by Daylight is a ...,[Action],"[Multi-player, PvP, Online PvP, Co-op, Online ...",492443,80,10.00
38442,10,Counter-Strike,Overwhelmingly Positive,Play the world's number 1 online action game. ...,[Action],"[Multi-player, PvP, Online PvP, Shared/Split S...",136118,97,9.99
38759,383150,Dead Island Definitive Edition,Very Positive,The game that re-defined the zombie genre - fu...,[Action],"[Single-player, Multi-player, Co-op, Online Co...",16951,82,2.99
9326,220,Half-Life 2,Overwhelmingly Positive,1998. HALF-LIFE sends a shock through the game...,[Action],"[Single-player, Steam Achievements, Steam Trad...",122230,97,9.99
38607,240720,Getting Over It with Bennett Foddy,Very Positive,A game I made For a certain kind of person To ...,[Action],"[Single-player, Partial Controller Support, Co...",54728,83,7.99
38449,400,Portal,Overwhelmingly Positive,Portal&trade; is a new single player game from...,[Action],"[Single-player, Steam Achievements, Captions a...",117868,98,10.00
38444,240,Counter-Strike: Source,Overwhelmingly Positive,THE NEXT INSTALLMENT OF THE WORLD'S # 1 ONLINE...,[Action],"[Multi-player, Cross-Platform Multiplayer, Ste...",103720,96,9.99
11012,581320,Insurgency: Sandstorm,Very Positive,"Insurgency: Sandstorm is a team-based, tactica...",[Action],"[Multi-player, PvP, Online PvP, Co-op, Online ...",85811,86,10.00

In [35]:
# Insurgency Sandstorm
rec = recommend(df, 581320, cs_matrix)
rec[['app_id', 'title', 'rating', 'about_the_game', 'genres', 'categories', 'user_reviews', 'positive_ratio', 'price_final']]

,app_id,title,rating,about_the_game,genres,categories,user_reviews,positive_ratio,price_final
38444,240,Counter-Strike: Source,Overwhelmingly Positive,THE NEXT INSTALLMENT OF THE WORLD'S # 1 ONLINE...,[Action],"[Multi-player, Cross-Platform Multiplayer, Ste...",103720,96,9.99
9326,220,Half-Life 2,Overwhelmingly Positive,1998. HALF-LIFE sends a shock through the game...,[Action],"[Single-player, Steam Achievements, Steam Trad...",122230,97,9.99
38449,400,Portal,Overwhelmingly Positive,Portal&trade; is a new single player game from...,[Action],"[Single-player, Steam Achievements, Captions a...",117868,98,10.00
38442,10,Counter-Strike,Overwhelmingly Positive,Play the world's number 1 online action game. ...,[Action],"[Multi-player, PvP, Online PvP, Shared/Split S...",136118,97,9.99
38443,70,Half-Life,Overwhelmingly Positive,Named Game of the Year by over 50 publications...,[Action],"[Single-player, Multi-player, PvP, Online PvP,...",72475,96,9.99
38607,240720,Getting Over It with Bennett Foddy,Very Positive,A game I made For a certain kind of person To ...,[Action],"[Single-player, Partial Controller Support, Co...",54728,83,7.99
41104,250900,The Binding of Isaac: Rebirth,Overwhelmingly Positive,When Isaac’s mother starts hearing the voice o...,[Action],"[Single-player, Multi-player, Shared/Split Scr...",225815,97,15.00
38531,55230,Saints Row: The Third,Overwhelmingly Positive,"Years after taking Stilwater for their own, th...",[Action],"[Single-player, Multi-player, Co-op, Steam Ach...",46587,95,9.99
38465,6060,Star Wars: Battlefront 2 (Classic 2005),Very Positive,"With brand new space combat, playable Jedi cha...",[Action],"[Single-player, Multi-player, PvP, Online PvP,...",42611,94,9.99
10327,304390,FOR HONOR™,Mixed,"Enter the chaos of war as a bold Knight, a bru...",[Action],"[Single-player, Multi-player, PvP, Online PvP,...",82277,69,15.00

In [36]:
# Halo The Master Chief Collection
rec = recommend(df, 976730, cs_matrix)
rec[['app_id', 'title', 'rating', 'about_the_game', 'genres', 'categories', 'user_reviews', 'positive_ratio', 'price_final']]

,app_id,title,rating,about_the_game,genres,categories,user_reviews,positive_ratio,price_final
11257,782330,DOOM Eternal,Very Positive,Hell’s armies have invaded Earth. Become the S...,[Action],"[Single-player, Multi-player, PvP, Online PvP,...",153466,91,40.00
9393,594650,Hunt: Showdown,Very Positive,"HUNT TOGETHER. DIE ALONE. The year is 1895, an...",[Action],"[Multi-player, PvP, Online PvP, Co-op, Online ...",136385,83,40.00
10700,548430,Deep Rock Galactic,Overwhelmingly Positive,Deep Rock Galactic is a 1-4 player co-op FPS f...,[Action],"[Single-player, Multi-player, Co-op, Online Co...",187823,97,30.00
11988,374320,DARK SOULS™ III,Very Positive,We are currently in the process of restoring t...,[Action],"[Single-player, Multi-player, Co-op, Steam Ach...",230407,94,30.00
38470,8870,BioShock Infinite,Very Positive,"Indebted to the wrong people, with his life on...",[Action],"[Single-player, Steam Achievements, Full contr...",99379,93,30.00
39209,1057090,Ori and the Will of the Wisps,Overwhelmingly Positive,ORI AND THE WILL OF THE WISPS IS A MUST PLAY*:...,[Action],"[Single-player, Steam Achievements, Full contr...",104440,96,29.99
9415,582010,Monster Hunter: World,Very Positive,Welcome to a new world! Take on the role of a ...,[Action],"[Single-player, Multi-player, Co-op, Steam Ach...",233430,87,30.00
39360,1238810,Battlefield™ V,Mostly Positive,This is the ultimate Battlefield V experience....,[Action],"[Single-player, Multi-player, PvP, Online PvP,...",141836,70,50.00
9772,412020,Metro Exodus,Very Positive,The year is 2036. A quarter-century after nucl...,[Action],"[Single-player, Steam Achievements, Full contr...",82022,89,30.00
39108,883710,Resident Evil 2,Overwhelmingly Positive,The genre-defining masterpiece Resident Evil 2...,[Action],"[Single-player, Steam Achievements, Full contr...",93910,97,40.00

In [37]:
# Doom Eternal
rec = recommend(df, 976730, cs_matrix)
rec[['app_id', 'title', 'rating', 'about_the_game', 'genres', 'categories', 'user_reviews', 'positive_ratio', 'price_final']]

,app_id,title,rating,about_the_game,genres,categories,user_reviews,positive_ratio,price_final
11257,782330,DOOM Eternal,Very Positive,Hell’s armies have invaded Earth. Become the S...,[Action],"[Single-player, Multi-player, PvP, Online PvP,...",153466,91,40.00
9393,594650,Hunt: Showdown,Very Positive,"HUNT TOGETHER. DIE ALONE. The year is 1895, an...",[Action],"[Multi-player, PvP, Online PvP, Co-op, Online ...",136385,83,40.00
10700,548430,Deep Rock Galactic,Overwhelmingly Positive,Deep Rock Galactic is a 1-4 player co-op FPS f...,[Action],"[Single-player, Multi-player, Co-op, Online Co...",187823,97,30.00
11988,374320,DARK SOULS™ III,Very Positive,We are currently in the process of restoring t...,[Action],"[Single-player, Multi-player, Co-op, Steam Ach...",230407,94,30.00
38470,8870,BioShock Infinite,Very Positive,"Indebted to the wrong people, with his life on...",[Action],"[Single-player, Steam Achievements, Full contr...",99379,93,30.00
39209,1057090,Ori and the Will of the Wisps,Overwhelmingly Positive,ORI AND THE WILL OF THE WISPS IS A MUST PLAY*:...,[Action],"[Single-player, Steam Achievements, Full contr...",104440,96,29.99
9415,582010,Monster Hunter: World,Very Positive,Welcome to a new world! Take on the role of a ...,[Action],"[Single-player, Multi-player, Co-op, Steam Ach...",233430,87,30.00
39360,1238810,Battlefield™ V,Mostly Positive,This is the ultimate Battlefield V experience....,[Action],"[Single-player, Multi-player, PvP, Online PvP,...",141836,70,50.00
9772,412020,Metro Exodus,Very Positive,The year is 2036. A quarter-century after nucl...,[Action],"[Single-player, Steam Achievements, Full contr...",82022,89,30.00
39108,883710,Resident Evil 2,Overwhelmingly Positive,The genre-defining masterpiece Resident Evil 2...,[Action],"[Single-player, Steam Achievements, Full contr...",93910,97,40.00

In [38]:
# Geometry Dash
rec = recommend(df, 322170, cs_matrix)
rec[['app_id', 'title', 'rating', 'about_the_game', 'genres', 'categories', 'user_reviews', 'positive_ratio', 'price_final']]

,app_id,title,rating,about_the_game,genres,categories,user_reviews,positive_ratio,price_final
9775,552500,Warhammer: Vermintide 2,Very Positive,Warhammer: Vermintide 2 is a 4-player co-op ac...,"[Action, Indie]","[Single-player, Multi-player, Co-op, Online Co...",73972,84,6.00
38576,219150,Hotline Miami,Overwhelmingly Positive,Hotline Miami is a high-octane action game ove...,"[Action, Indie]","[Single-player, Steam Achievements, Full contr...",70877,97,9.99
1135,221640,Super Hexagon,Overwhelmingly Positive,Super Hexagon is a minimal action game by Terr...,"[Action, Indie]","[Single-player, Full controller support]",17074,97,2.99
2601,323850,Move or Die,Very Positive,"20 seconds, constantly changing mechanics and ...","[Action, Indie]","[Single-player, Multi-player, PvP, Online PvP,...",15395,90,3.74
11120,268910,Cuphead,Overwhelmingly Positive,Cuphead is a classic run and gun action game h...,"[Action, Indie]","[Single-player, Multi-player, Co-op, Shared/Sp...",128002,96,20.00
39275,1147560,Skul: The Hero Slayer,Very Positive,The Demon King's Castle in Ruins The human rac...,"[Action, Indie]","[Single-player, Full controller support, Steam...",37828,93,11.99
9839,1557740,ROUNDS,Overwhelmingly Positive,Wave your noodle arms around to assert dominan...,"[Action, Indie]","[Multi-player, PvP, Online PvP, Shared/Split S...",17212,95,6.00
38830,460950,Katana ZERO,Overwhelmingly Positive,"Katana ZERO is a stylish neo-noir, action-plat...","[Action, Indie]","[Single-player, Steam Achievements, Full contr...",51364,98,14.99
10070,632360,Risk of Rain 2,Overwhelmingly Positive,SURVIVE AN ALIEN PLANET Over a dozen handcraft...,"[Action, Indie]","[Single-player, Multi-player, PvP, Online PvP,...",164702,96,25.00
38641,274170,Hotline Miami 2: Wrong Number,Very Positive,Hotline Miami 2: Wrong Number is the brutal co...,"[Action, Indie]","[Single-player, Steam Achievements, Full contr...",42431,93,14.99

In [39]:
# Rocketbirds 2 Evolution
rec = recommend(df, 470210, cs_matrix)
rec[['app_id', 'title', 'rating', 'about_the_game', 'genres', 'categories', 'user_reviews', 'positive_ratio', 'price_final']]

,app_id,title,rating,about_the_game,genres,categories,user_reviews,positive_ratio,price_final
16677,788810,Exposure,Mixed,It's been several weeks since the terrible car...,"[Violent, Action, Adventure, Indie]","[Single-player, Partial Controller Support]",28,50,2.99
38627,253430,CastleMiner Z,Very Positive,CastleMiner Z is an online coop survival horro...,"[Violent, Action, Adventure, Indie]","[Single-player, Multi-player, PvP, Online PvP,...",7070,81,3.99
37968,890880,FROSTBITE: Deadly Climate,Very Positive,A lone Arctic Biologist ends up getting lost i...,"[Violent, Action, Adventure, Indie]","[Single-player, Steam Achievements]",494,87,0.00
32122,729090,Tropical Escape,Negative,Experience what is like to be on stranded isla...,"[Violent, Action, Adventure, Indie]","[Single-player, Steam Achievements, Steam Cloud]",24,16,1.99
24514,417920,Mistfal,Mixed,Description: Mistfal is a psychological thrill...,"[Violent, Action, Adventure, Indie]","[Single-player, Steam Trading Cards, Partial C...",56,46,0.00
21648,675510,Kingdom City Drowning Episode 1 - The Champion,Mostly Negative,***PAUSE THE EXPERIENCE TO CHANGE GRAPHICS SET...,"[Violent, Action, Adventure, Indie]","[Single-player, Partial Controller Support]",13,30,4.99
13685,584990,The Long Reach,Very Positive,"'Calm down. This is all normal. Well, it’s a n...","[Violent, Gore, Action, Adventure, Indie]","[Single-player, Full controller support, Remot...",308,87,14.99
5061,605830,Organ Quarter,Very Positive,What is Organ Quarter? Organ Quarter is a VR s...,"[Violent, Gore, Action, Adventure, Indie]",[Single-player],260,89,24.99
26608,596240,Apocryph: an old-school shooter,Mixed,Apocryph is a FPS set in a brutal dark fantasy...,"[Violent, Gore, Action, Adventure, Indie]","[Single-player, Steam Achievements, Steam Trad...",267,50,14.99
7175,622770,Hacktag,Mostly Positive,Hacktag is a 2-player co-op stealth-game with ...,"[Action, Adventure, Indie]","[Single-player, Multi-player, PvP, Online PvP,...",282,70,9.99